### ISSUE TITLE
async_refactor branch checklist

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#136]
Stuff to be done before release:

- [x] Finish logging
- [x] Address name resolving step should be interruptible -- currently I can't do e.g. `/connect` if the task is blocked on `getsockaddr()`. Similarly I can't quit.
- [x] SASL authentication
- [x] Implement sending pings on timeout.
- [x] Reconnecting after a disconnect does not work.
- [x] `C-c` does not really quit -- it closes the connections (I think, at least it sends QUIT messages) but the TUI hangs.
- [x] Port 1d2a690
- [x] ~~Find a way to disable stderr logging in release build~~ Use env_logger for debug logs

**Comment by osa1** [comment]
Almost done!

**Comment by osa1** [comment]
There are still a few `await`s in the client main loop that blocks the client; those should be refactored:

- [ ] The `addr_iter` await call
- [ ] The delay when address name resolve fails
- [ ] The delay when connection fails (after address name resolving)

Also, it seems like we currently try to reconnect immediately when connection fails *after* it's established. This is different than the previous behavior where we waited for 30 seconds or so.

**Comment by osa1** [comment]
We have PR now and we'll track progress there.
