### ISSUE TITLE
rustls support checklist

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#173]
#172 makes two changes:

- We now parse certs only once (instead of one per connection)
- Support for using rustls library for TLS connections (opt-in)

TODOs:

- [ ] Announce the changes in CHANGELOG
- [ ] Give a description of how to install tiny with rustls in README
- [x] Test rustls build in CI
